import { makeDiff } from '../lib/diff';
import { applyPatch } from '../lib/patch';

describe('diff and patch process', () => {
    it('should correctly apply patch generated by makeDiff', async () => {
        // 初期状態の JSON
        const originalJson = {
            users: [
                { id: 1, name: "John Doe", email: "john@example.com" },
                { id: 2, name: "Jane Doe", email: "jane@example.com" }
            ],
            tasks: [
                { id: 1, title: "Task 1", completed: false },
                { id: 2, title: "Task 2", completed: true }
            ]
        };

        // 変更後の状態の JSON
        const updatedJson = {
            users: [
                { id: 1, name: "John Doe", email: "john.doe@example.com" }, // Email updated
                { id: 2, name: "Jane Doe", email: "jane@example.com" },
                { id: 3, name: "Jake Doe", email: "jake@example.com" } // New user added
            ],
            tasks: [
                { id: 1, title: "Task 1", completed: true }, // Task completed
                // Task 2 removed
            ]
        };

        // makeDiff を使用して差分を計算
        const patch = makeDiff(originalJson, updatedJson);

        // applyPatch を使用して差分を適用
        const resultJson = await applyPatch(originalJson, patch);

        // 結果が updatedJson と等しいか検証
        expect(resultJson).toEqual(updatedJson);
    });
});